language: node_js

node_js:
#  - 4
  - 6
  - 7

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
  yarn: true

script:
  - yarn lib
  - yarn test:stylelint
  - yarn test -- --coverage

after_success: yarn coveralls
