language: node_js

node_js:
#  - 4
  - 6
  - 7

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
    - e2e/node_modules
  yarn: true

script:
  - yarn eslint
  - yarn flow
  - yarn lib
  - yarn test:stylelint
  - yarn test -- --coverage
  # E2E
  - cd e2e
  - yarn --pure-lock
  - yarn add file:$PWD/..
  - yarn test

after_success: yarn coveralls
